name: fnd-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - flask=3.0.3
  - joblib=1.4.2
  - scikit-learn=1.5.1
  - numpy=2.0.1
  - scipy=1.14.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - threadpoolctl=3.5.0
  - tbb=2021.8.0
  - pip
  - pip:
      - aniso8601==9.0.1
      - blinker==1.8.2
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - filelock==3.15.4
      - Flask-RESTful==0.3.10
      - fsspec==2024.6.1
      - gunicorn==22.0.0
      - huggingface-hub==0.24.5
      - idna==3.7
      - itsdangerous==2.2.0
      - Jinja2==3.1.4
      - MarkupSafe==2.1.5
      - packaging==24.1
      - pytz==2024.1
      - PyYAML==6.0.2
      - regex==2024.7.24
      - requests==2.32.3
      - safetensors==0.4.4
      - six==1.16.0
      - tokenizers==0.19.1
      - tqdm==4.66.5
      - transformers==4.44.0
      - typing-extensions==4.12.2
      - urllib3==2.2.2
      - Werkzeug==3.0.3
      - wheel==0.43.0
