name: fnd-env
channels:
  - defaults
dependencies:
  - pip=24.2
  - python=3.11.10
  - pip:
      - flask==3.0.3
      - joblib==1.4.2
      - numpy==2.1.2
      - requests==2.32.3
      - scikit-learn==1.4.2

      Flask==3.0.3
Flask-RESTful==0.3.10
scikit-learn==1.4.2
joblib==1.4.2